"""Move effects dictionary and lookup helper."""
from __future__ import annotations

MOVE_EFFECTS: dict[str, dict] = {
    # ── Statut pur ────────────────────────────────────────────────────────
    "thunder-wave":     {"status": "PAR", "target": "foe", "acc_override": 100},
    "stun-spore":       {"status": "PAR", "target": "foe"},
    "glare":            {"status": "PAR", "target": "foe"},
    "sleep-powder":     {"status": "SLP", "target": "foe"},
    "spore":            {"status": "SLP", "target": "foe", "acc_override": 100},
    "hypnosis":         {"status": "SLP", "target": "foe"},
    "sing":             {"status": "SLP", "target": "foe"},
    "lovely-kiss":      {"status": "SLP", "target": "foe"},
    "poison-powder":    {"status": "PSN", "target": "foe"},
    "poison-gas":       {"status": "PSN", "target": "foe"},
    "toxic":            {"status": "TOX", "target": "foe"},
    "will-o-wisp":      {"status": "BRN", "target": "foe"},
    "confuse-ray":      {"confuse": True, "target": "foe", "acc_override": 100},
    "supersonic":       {"confuse": True, "target": "foe"},
    "sweet-kiss":       {"confuse": True, "target": "foe"},
    "teeter-dance":     {"confuse": True, "target": "foe", "acc_override": 100},
    # ── Baisser stats adverses ────────────────────────────────────────────
    "growl":            {"stages": {"atk": -1}, "target": "foe"},
    "leer":             {"stages": {"def": -1}, "target": "foe"},
    "tail-whip":        {"stages": {"def": -1}, "target": "foe"},
    "sand-attack":      {"stages": {"acc": -1}, "target": "foe"},
    "smokescreen":      {"stages": {"acc": -1}, "target": "foe"},
    "kinesis":          {"stages": {"acc": -1}, "target": "foe"},
    "flash":            {"stages": {"acc": -1}, "target": "foe"},
    "string-shot":      {"stages": {"spe": -1}, "target": "foe"},
    "screech":          {"stages": {"def": -2}, "target": "foe"},
    "charm":            {"stages": {"atk": -2}, "target": "foe"},
    "feather-dance":    {"stages": {"atk": -2}, "target": "foe"},
    "fake-tears":       {"stages": {"spd": -2}, "target": "foe"},
    "metal-sound":      {"stages": {"spd": -2}, "target": "foe"},
    "tickle":           {"stages": {"atk": -1, "def": -1}, "target": "foe"},
    "captivate":        {"stages": {"spa": -2}, "target": "foe"},
    # ── Monter ses propres stats ──────────────────────────────────────────
    "swords-dance":     {"stages": {"atk": +2}, "target": "self"},
    "meditate":         {"stages": {"atk": +1}, "target": "self"},
    "sharpen":          {"stages": {"atk": +1}, "target": "self"},
    "agility":          {"stages": {"spe": +2}, "target": "self"},
    "double-team":      {"stages": {"eva": +1}, "target": "self"},
    "minimize":         {"stages": {"eva": +2}, "target": "self"},
    "barrier":          {"stages": {"def": +2}, "target": "self"},
    "harden":           {"stages": {"def": +1}, "target": "self"},
    "withdraw":         {"stages": {"def": +1}, "target": "self"},
    "defense-curl":     {"stages": {"def": +1}, "target": "self"},
    "acid-armor":       {"stages": {"def": +2}, "target": "self"},
    "amnesia":          {"stages": {"spa": +2}, "target": "self"},
    "calm-mind":        {"stages": {"spa": +1, "spd": +1}, "target": "self"},
    "nasty-plot":       {"stages": {"spa": +2}, "target": "self"},
    "growth":           {"stages": {"spa": +1}, "target": "self"},
    "howl":             {"stages": {"atk": +1}, "target": "self"},
    "bulk-up":          {"stages": {"atk": +1, "def": +1}, "target": "self"},
    "dragon-dance":     {"stages": {"atk": +1, "spe": +1}, "target": "self"},
    "quiver-dance":     {"stages": {"spa": +1, "spd": +1, "spe": +1}, "target": "self"},
    "shift-gear":       {"stages": {"atk": +1, "spe": +2}, "target": "self"},
    "coil":             {"stages": {"atk": +1, "def": +1}, "target": "self"},
    # ── Soin ─────────────────────────────────────────────────────────────
    "recover":          {"heal": 0.5},
    "softboiled":       {"heal": 0.5},
    "soft-boiled":      {"heal": 0.5},
    "rest":             {"heal": 1.0, "rest_sleep": True},
    "synthesis":        {"heal": 0.5},
    "moonlight":        {"heal": 0.5},
    "morning-sun":      {"heal": 0.5},
    "roost":            {"heal": 0.5},
    "slack-off":        {"heal": 0.5},
    "heal-order":       {"heal": 0.5},
    "milk-drink":       {"heal": 0.5},
    # ── Haze ─────────────────────────────────────────────────────────────
    "haze":             {"haze": True},
    # ── Dégâts fixes ─────────────────────────────────────────────────────
    "sonic-boom":       {"damage": True, "fixed_dmg": 20},
    "dragon-rage":      {"damage": True, "fixed_dmg": 40},
    # ── Dégâts = niveau ──────────────────────────────────────────────────
    "seismic-toss":     {"damage": True, "level_dmg": True},
    "night-shade":      {"damage": True, "level_dmg": True},
    # ── OHKO ─────────────────────────────────────────────────────────────
    "guillotine":       {"damage": True, "ohko": True, "acc_override": 30},
    "fissure":          {"damage": True, "ohko": True, "acc_override": 30},
    "horn-drill":       {"damage": True, "ohko": True, "acc_override": 30},
    "sheer-cold":       {"damage": True, "ohko": True, "acc_override": 30},
    # ── Explosion / Auto-destruction ─────────────────────────────────────
    "self-destruct":    {"damage": True, "self_destruct": True},
    "explosion":        {"damage": True, "self_destruct": True},
    # ── Recharge (Hyper Beam etc.) ────────────────────────────────────────
    "hyper-beam":       {"damage": True, "recharge": True},
    "giga-impact":      {"damage": True, "recharge": True},
    "frenzy-plant":     {"damage": True, "recharge": True},
    "blast-burn":       {"damage": True, "recharge": True},
    "hydro-cannon":     {"damage": True, "recharge": True},
    "rock-wrecker":     {"damage": True, "recharge": True},
    "roar-of-time":     {"damage": True, "recharge": True},
    # ── Coups critiques élevés ────────────────────────────────────────────
    "karate-chop":      {"damage": True, "high_crit": True},
    "slash":            {"damage": True, "high_crit": True},
    "razor-leaf":       {"damage": True, "high_crit": True},
    "crabhammer":       {"damage": True, "high_crit": True},
    "aeroblast":        {"damage": True, "high_crit": True},
    "cross-chop":       {"damage": True, "high_crit": True},
    "sky-attack":       {"damage": True, "high_crit": True},
    "stone-edge":       {"damage": True, "high_crit": True},
    "night-slash":      {"damage": True, "high_crit": True},
    "leaf-blade":       {"damage": True, "high_crit": True},
    "psycho-cut":       {"damage": True, "high_crit": True},
    "razor-wind":       {"damage": True, "high_crit": True},
    "x-scissor":        {"damage": True, "high_crit": True},
    "spacial-rend":     {"damage": True, "high_crit": True},
    # ── Multi-coups ──────────────────────────────────────────────────────
    "double-slap":      {"damage": True, "multi_hit": True},
    "comet-punch":      {"damage": True, "multi_hit": True},
    "fury-attack":      {"damage": True, "multi_hit": True},
    "pin-missile":      {"damage": True, "multi_hit": True},
    "spike-cannon":     {"damage": True, "multi_hit": True},
    "twineedle":        {"damage": True, "multi_hit": (2, 2), "status": "PSN", "target": "foe", "chance": 20},
    "bone-rush":        {"damage": True, "multi_hit": True},
    "fury-swipes":      {"damage": True, "multi_hit": True},
    "barrage":          {"damage": True, "multi_hit": True},
    "arm-thrust":       {"damage": True, "multi_hit": True},
    "bullet-seed":      {"damage": True, "multi_hit": True},
    "rock-blast":       {"damage": True, "multi_hit": True},
    "icicle-spear":     {"damage": True, "multi_hit": True},
    "double-hit":       {"damage": True, "multi_hit": (2, 2)},
    "dual-chop":        {"damage": True, "multi_hit": (2, 2)},
    "bonemerang":       {"damage": True, "multi_hit": (2, 2)},
    "double-kick":      {"damage": True, "multi_hit": (2, 2)},
    "gear-grind":       {"damage": True, "multi_hit": (2, 2)},
    "triple-kick":      {"damage": True, "multi_hit": (3, 3)},
    "tail-slap":        {"damage": True, "multi_hit": True},
    # ── Drain ─────────────────────────────────────────────────────────────
    "absorb":           {"damage": True, "drain": 0.5},
    "mega-drain":       {"damage": True, "drain": 0.5},
    "giga-drain":       {"damage": True, "drain": 0.5},
    "leech-life":       {"damage": True, "drain": 0.5},
    "dream-eater":      {"damage": True, "drain": 0.5, "drain_sleep_only": True},
    "draining-kiss":    {"damage": True, "drain": 0.75},
    "parabolic-charge": {"damage": True, "drain": 0.5},
    "horn-leech":       {"damage": True, "drain": 0.5},
    # ── Recul ─────────────────────────────────────────────────────────────
    "take-down":        {"damage": True, "recoil": 0.25},
    "double-edge":      {"damage": True, "recoil": 0.33},
    "submission":       {"damage": True, "recoil": 0.25},
    "brave-bird":       {"damage": True, "recoil": 0.33},
    "head-smash":       {"damage": True, "recoil": 0.5},
    "volt-tackle":      {"damage": True, "recoil": 0.33, "status": "PAR", "target": "foe", "chance": 10},
    "wood-hammer":      {"damage": True, "recoil": 0.33},
    "wild-charge":      {"damage": True, "recoil": 0.25},
    "flare-blitz":      {"damage": True, "recoil": 0.33, "status": "BRN", "target": "foe", "chance": 10},
    # ── Brûlure secondaire ────────────────────────────────────────────────
    "ember":            {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    "flamethrower":     {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    "fire-blast":       {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    "fire-punch":       {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    "heat-wave":        {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    "lava-plume":       {"damage": True, "status": "BRN", "target": "foe", "chance": 30},
    "scald":            {"damage": True, "status": "BRN", "target": "foe", "chance": 30},
    "sacred-fire":      {"damage": True, "status": "BRN", "target": "foe", "chance": 50},
    "blaze-kick":       {"damage": True, "status": "BRN", "target": "foe", "chance": 10},
    # ── Gel secondaire ────────────────────────────────────────────────────
    "blizzard":         {"damage": True, "status": "FRZ", "target": "foe", "chance": 10},
    "ice-beam":         {"damage": True, "status": "FRZ", "target": "foe", "chance": 10},
    "ice-punch":        {"damage": True, "status": "FRZ", "target": "foe", "chance": 10},
    "powder-snow":      {"damage": True, "status": "FRZ", "target": "foe", "chance": 10},
    "freeze-dry":       {"damage": True, "status": "FRZ", "target": "foe", "chance": 10},
    "tri-attack":       {"damage": True, "status": "any_bpf", "target": "foe", "chance": 20},
    # ── Paralysie secondaire ──────────────────────────────────────────────
    "body-slam":        {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "thunder":          {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "thunderbolt":      {"damage": True, "status": "PAR", "target": "foe", "chance": 10},
    "thunder-punch":    {"damage": True, "status": "PAR", "target": "foe", "chance": 10},
    "spark":            {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "discharge":        {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "force-palm":       {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "bounce":           {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    "nuzzle":           {"damage": True, "status": "PAR", "target": "foe", "chance": 100},
    "lick":             {"damage": True, "status": "PAR", "target": "foe", "chance": 30},
    # ── Empoisonnement secondaire ─────────────────────────────────────────
    "poison-sting":     {"damage": True, "status": "PSN", "target": "foe", "chance": 30},
    "sludge":           {"damage": True, "status": "PSN", "target": "foe", "chance": 30},
    "sludge-bomb":      {"damage": True, "status": "PSN", "target": "foe", "chance": 30},
    "sludge-wave":      {"damage": True, "status": "PSN", "target": "foe", "chance": 10},
    "smog":             {"damage": True, "status": "PSN", "target": "foe", "chance": 40},
    "cross-poison":     {"damage": True, "status": "PSN", "target": "foe", "chance": 10},
    "gunk-shot":        {"damage": True, "status": "PSN", "target": "foe", "chance": 30},
    "poison-jab":       {"damage": True, "status": "PSN", "target": "foe", "chance": 30},
    # ── Confusion secondaire ──────────────────────────────────────────────
    "confusion":        {"damage": True, "confuse": True, "target": "foe", "chance": 10},
    "psybeam":          {"damage": True, "confuse": True, "target": "foe", "chance": 10},
    "dizzy-punch":      {"damage": True, "confuse": True, "target": "foe", "chance": 20},
    "water-pulse":      {"damage": True, "confuse": True, "target": "foe", "chance": 20},
    "signal-beam":      {"damage": True, "confuse": True, "target": "foe", "chance": 10},
    "hurricane":        {"damage": True, "confuse": True, "target": "foe", "chance": 30},
    "dynamic-punch":    {"damage": True, "confuse": True, "target": "foe", "chance": 100},
    "chatter":          {"damage": True, "confuse": True, "target": "foe", "chance": 10},
    # ── Baisser stats adverses (sur dégâts) ──────────────────────────────
    "acid":             {"damage": True, "stages": {"def": -1},  "target": "foe", "chance": 10},
    "bubble":           {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 10},
    "bubble-beam":      {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 33},
    "constrict":        {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 10},
    "rock-smash":       {"damage": True, "stages": {"def": -1},  "target": "foe", "chance": 50},
    "crunch":           {"damage": True, "stages": {"def": -1},  "target": "foe", "chance": 20},
    "shadow-ball":      {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 20},
    "energy-ball":      {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 10},
    "psychic":          {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 10},
    "earth-power":      {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 10},
    "flash-cannon":     {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 10},
    "moonblast":        {"damage": True, "stages": {"spa": -1},  "target": "foe", "chance": 30},
    "muddy-water":      {"damage": True, "stages": {"acc": -1},  "target": "foe", "chance": 30},
    "mud-slap":         {"damage": True, "stages": {"acc": -1},  "target": "foe", "chance": 100},
    "icy-wind":         {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "bulldoze":         {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "electroweb":       {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "low-sweep":        {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "rock-tomb":        {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "mud-shot":         {"damage": True, "stages": {"spe": -1},  "target": "foe", "chance": 100},
    "aurora-beam":      {"damage": True, "stages": {"atk": -1},  "target": "foe", "chance": 10},
    "luster-purge":     {"damage": True, "stages": {"spd": -1},  "target": "foe", "chance": 50},
    "mist-ball":        {"damage": True, "stages": {"spa": -1},  "target": "foe", "chance": 50},
    # ── Deux tours de charge ─────────────────────────────────────────────
    "fly":          {"damage": True, "two_turn": True, "charge_msg": "s'élance dans les airs !"},
    "dig":          {"damage": True, "two_turn": True, "charge_msg": "creuse sous le sol !"},
    "solar-beam":   {"damage": True, "two_turn": True, "charge_msg": "absorbe l'énergie solaire !"},
    "skull-bash":   {"damage": True, "two_turn": True, "charge_msg": "baisse la tête !", "stages": {"def": +1}, "target": "self"},
    "sky-attack":   {"damage": True, "two_turn": True, "high_crit": True, "charge_msg": "cherche la cible !"},
    "razor-wind":   {"damage": True, "two_turn": True, "high_crit": True, "charge_msg": "prépare ses lames !"},
    # ── Attaques verrous (Triplattaque, Pétale-Danse…) ───────────────────
    "thrash":       {"damage": True, "lock_move": True},
    "petal-dance":  {"damage": True, "lock_move": True},
    "outrage":      {"damage": True, "lock_move": True},
    # ── Pièges (Ligotage, Étreinte, Tourbifeu, Kraid…) ──────────────────
    "wrap":         {"damage": True, "trap": True},
    "bind":         {"damage": True, "trap": True},
    "fire-spin":    {"damage": True, "trap": True},
    "clamp":        {"damage": True, "trap": True},
    # ── Effets de terrain / protection ───────────────────────────────────
    "leech-seed":   {"leech_seed": True, "acc_override": 90},
    "light-screen": {"light_screen": True},
    "reflect":      {"reflect_move": True},
    "mist":         {"mist_move": True},
    "focus-energy": {"focus_energy": True},
    # ── Désactivation ────────────────────────────────────────────────────
    "disable":      {"disable_move": True},
    # ── Imitation / transformation ────────────────────────────────────────
    "mimic":        {"mimic": True},
    "mirror-move":  {"mirror_move": True},
    "metronome":    {"metronome": True},
    "transform":    {"transform": True},
    "sketch":       {"mimic": True},
    "copycat":      {"mirror_move": True},
    # ── Riposte / accumulation ────────────────────────────────────────────
    "counter":      {"counter": True},
    "bide":         {"bide": True},
    "rage":         {"damage": True, "rage": True},
    # ── Divers ────────────────────────────────────────────────────────────
    "conversion":   {"conversion": True},
    "whirlwind":    {"end_wild": True},
    "roar":         {"end_wild": True},
    "teleport":     {"end_wild": True},
    "swift":        {"damage": True, "acc_override": 100},
    "super-fang":   {"damage": True, "half_hp": True},
    "psywave":      {"damage": True, "psywave": True},
    "pay-day":      {"damage": True},
    "splash":       {},
    # ── Monter stats propres (sur dégâts) ────────────────────────────────
    "charge-beam":      {"damage": True, "stages": {"spa": +1}, "target": "self", "chance": 70},
    "meteor-mash":      {"damage": True, "stages": {"atk": +1}, "target": "self", "chance": 20},
    "steel-wing":       {"damage": True, "stages": {"def": +1}, "target": "self", "chance": 10},
    "ancient-power":    {"damage": True, "stages": {"atk": +1, "def": +1, "spa": +1, "spd": +1, "spe": +1}, "target": "self", "chance": 10},
    "silver-wind":      {"damage": True, "stages": {"atk": +1, "def": +1, "spa": +1, "spd": +1, "spe": +1}, "target": "self", "chance": 10},
    "ominous-wind":     {"damage": True, "stages": {"atk": +1, "def": +1, "spa": +1, "spd": +1, "spe": +1}, "target": "self", "chance": 10},
}


def lookup_effect(move_sym: str) -> dict:
    """Retourne le dictionnaire d'effets pour un move donné."""
    return MOVE_EFFECTS.get(move_sym.lower().replace("_", "-"), {})
